# Shared number of replicas (workers) for build and runtime
# This includes the broker
x-shared-workers:
  &workers
  replicas: 4

# Build args that go into building container
x-shared-build-args: &shared-build-args
  flux_sched_version: jammy
  <<: *workers
    
# Shared environment for runtime
x-shared-environment: &shared-environment
  SPL_BROKER_URL: amqp://fluxuser:fluxrabbit@rabbit:5672//
  mainHost: node-1
  workdir: /code/workdir
  <<: *workers

x-shared-volumes: &shared-volumes
  - ./flux/imp.toml:/etc/flux/imp/conf.d/imp.toml
  - ./flux/broker.toml:/etc/flux/config/broker.toml
  - ./:/code/workdir

services:
  rabbit:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=fluxuser
      - RABBITMQ_DEFAULT_PASS=fluxrabbit
   
  node-1:
    build:
      context: ./
      args: *shared-build-args
    hostname: node-1
    container_name: node-1
    networks:
      - rabbitmq
    environment: *shared-environment
    volumes: *shared-volumes

  node-2:
    build:
      context: ./
      args: *shared-build-args
    hostname: node-2      
    container_name: node-2
    networks:
      - rabbitmq
    environment: *shared-environment
    volumes: *shared-volumes

  node-3:
    build:
      context: ./
      args: *shared-build-args
    hostname: node-3
    container_name: node-3
    networks:
      - rabbitmq
    environment: *shared-environment
    volumes: *shared-volumes

  node-4:
    build:
      context: ./
      args: *shared-build-args
    container_name: node-4
    hostname: node-4
    networks:
      - rabbitmq
    environment: *shared-environment
    volumes: *shared-volumes

networks:
  rabbitmq:
    driver: bridge
